### ISSUE TITLE
database design for users, customers, employees, and suppliers

### ISSUE THREAD

**Issue by 341megaman** [mharoot/ElegantMVC#3]
@marvinh @mharoot @cbuntrakulsuk  customers, employees, and suppliers table need an UserID field for optimization for some of my functions in customer_model @ reviewBillingInformation().

Will it be easier to use $_SESSION since we will be logged in?

**Comment by mharoot** [comment]
@341megaman @marvinh @cbuntrakulsuk 
I have updated to users table to include all our current customers, employees, and suppliers.  You can now use $_SESSION['user_id'] to establish a one to one relation with the users table.  Should simplify things greatly.
