### ISSUE TITLE
Routing System fix

### ISSUE THREAD

**Issue by marvinh** [mharoot/ElegantMVC#5]
Routing
Previously we had a terrible routing system in which we required our routes to be named after our controller files. In order to go to other routes we had to call something like example.com/ControllerName/ViewActionFunction

This was not the correct architecture for an MVC application.  What it was actually doing was calling the view functions instead of a controller function  which is not the correct way to set up an MVC architecture. The new ```Router``` class takes care of this for us. I will be submitting to my branch for review

in the index.php file declare your routes like so 
```php
//The slash here is the name of the route example.com/ 
// IndexController is the class its going to call
// index is the function
$router->addRoute("/","IndexController","index");

//The index in the first parameter here is the name of the route example.com/index
//IndexController is the class its going to call
// index is the function
$router->addRoute("index","IndexController","index");
``` 

If you need the same route for multiple controllers you would use the same name for both when 
you add the route like so 

```php
// This routes to the pages example.com/products
// call the Products Controller class displayProducts function
$router->addRoute("products","ProductController","displayProducts");
// This also routes to the pages example.com/products
// call the CategoryController class displayCategory function
$router->addRoute("products","CategoryController","displayCategory");
```
There is a last parameter which is an array which is optional
It acts as middleware and routes users to a forbidden page 
if they don't meet the requirement for that page
say there user_type = 4 but the page only allows user_types 1,2,and 3 
you would define it like so in your route
```php
$router->addRoute("route","Controller","function",array(1,2,3));
```
This would forbid that user from accessing that controller and function

**Comment by mharoot** [comment]
Can you explain where we need to add routes? @marvinh

**Comment by marvinh** [comment]
Index.php this may be moved later on in order to keep the authorizations private, but for now this is the working file for adding routes
